package com.asterite.remsh;

import java.util.ArrayList;
import java.util.List;

public class Characters {
	
	private final static List<String> characters = new ArrayList<String>();
	private final static List<String> keywords = new ArrayList<String>();
	private final static List<String> pinyins = new ArrayList<String>();
	
	public static int size() {
		return characters.size();
	}
	
	public static String getCharacter(int frame) {
		return characters.get(frame);
	}
	
	public static String getKeyword(int frame) {
		return keywords.get(frame);
	}
	
	public static String getPinyin(int frame) {
		return pinyins.get(frame);
	}
	
	static {
		add("一", "one", "yī");
		add("二", "two", "èr");
		add("三", "three", "sān");
		add("四", "four", "sì");
		add("五", "five", "wǔ");
		add("六", "six", "lìu");
		add("七", "seven", "qī");
		add("八", "eight", "bā");
		add("九", "nine", "jǐu");
		add("十", "ten", "shí");
		add("口", "mouth", "kǒu");
		add("日", "day", "rì");
		add("月", "month", "yuè");
		add("田", "rice field", "tián");
		add("目", "eye", "mù");
		add("古", "ancient", "gǔ");
		add("胡", "recklessly", "hú");
		add("叶", "leaf", "xié");
		add("吾", "I (literary)", "wú");
		add("朋", "companion", "péng");
		add("明", "bright", "míng");
		add("唱", "sing", "chàng");
		add("晶", "sparkling", "jīng");
		add("品", "goods", "pǐn");
		add("昌", "prosperous", "chāng");
		add("早", "early", "zǎo");
		add("旭", "rising sun", "xù");
		add("世", "generation", "shì");
		add("胃", "stomach", "wèi");
		add("旦", "daybreak", "dàn");
		add("凹", "concave", "āo");
		add("凸", "convex", "tū");
		add("自", "oneself", "zì");
		add("白", "white", "bái");
		add("百", "hundred", "bǎi");
		add("皂", "soap", "zào");
		add("旧", "old", "jìu");
		add("中", "middle", "zhōng");
		add("千", "thousand", "qiān");
		add("舌", "tongue", "shé");
		add("升", "liter", "shēng");
		add("丸", "pill", "wán");
		add("卜", "divination", "bǔ");
		add("占", "tell fortunes", "zhān");
		add("上", "above", "shàng");
		add("下", "below", "xià");
		add("卡", "card", "qiǎ");
		add("卓", "eminent", "zhūo");
		add("朝", "dynasty", "zhāo");
		add("嘲", "ridicule", "cháo");
		add("只", "only", "zhǐ");
		add("贝", "shellfish", "bèi");
		add("贴", "paste", "tiē");
		add("贞", "chaste", "zhēn");
		add("员", "employee", "yuán");
		add("儿", "youngster", "ér");
		add("几", "how many?", "jī");
		add("见", "see", "jiàn");
		add("元", "beginning", "yuán");
		add("页", "page", "yè");
		add("顽", "stubborn", "wán");
		add("凡", "ordinary", "fán");
		add("肌", "muscle", "jī");
		add("负", "defeated", "fù");
		add("万", "ten thousand", "wàn");
		add("匀", "uniform", "yún");
		add("句", "sentence", "jù");
		add("旬", "decameron", "xún");
		add("勺", "ladle", "sháo");
		add("的", "bull's eye", "de");
		add("首", "heads", "shǒu");
		add("直", "straight", "zhí");
		add("置", "setup", "zhì");
		add("具", "tool", "jù");
		add("真", "true ", "zhēn");
		add("工", "work", "gōng");
		add("左", "left", "zǔo");
		add("右", "right", "yòu");
		add("有", "possess", "yǒu");
		add("贿", "bribe", "hùi");
		add("贡", "tribute", "gòng");
		add("项", "item", "xiàng");
		add("刀", "sword", "dāo");
		add("刃", "blade", "rèn");
		add("切", "cut", "qiē");
		add("召", "summon", "zhào");
		add("昭", "evident", "zhāo");
		add("则", "rule", "zé");
		add("副", "vice-", "fù");
		add("丁", "fourth", "dīng");
		add("叮", "sting", "dīng");
		add("可", "can", "kĕ");
		add("哥", "older brother", "gē");
		add("顶", "crest", "dǐng");
		add("乙", "second", "yǐ");
		add("飞", "fly", "fēi");
		add("子", "child", "zǐ");
		add("孔", "cavity", "kǒng");
		add("吼", "roar", "hǒu");
		add("乱", "chaos", "luàn");
		add("了", "(-ed)", "le");
		add("女", "woman", "nǚ");
		add("好", "good", "hǎo");
		add("如", "be like", "rú");
		add("母", "mother", "mǔ");
		add("贯", "pierce", "guàn");
		add("兄", "elder brother", "xīong");
		add("克", "overcome", "kè");
		add("小", "small", "xiǎo");
		add("少", "few", "shǎo");
		add("吵", "noisy", "chǎo");
		add("孙", "grandchild", "sūn");
		add("大", "large", "dà");
		add("尖", "tip", "jiān");
		add("夕", "evening", "xī");
		add("多", "many", "dūo");
		add("够", "enough", "gòu");
		add("外", "outside", "wài");
		add("名", "name", "míng");
		add("罗", "silk gauze", "lūo");
		add("厂", "factory", "chǎng");
		add("厅", "hall", "tīng");
		add("厉", "stern", "lì");
		add("厚", "thick", "hòu");
		add("石", "stone", "shí");
		add("砂", "gravel", "shā");
		add("妙", "wonderful", "miào");
		add("肖", "resemble", "xiào");
		add("削", "peel", "xuē");
		add("光", "ray", "guāng");
		add("太", "overly", "tài");
		add("省", "economize", "shĕng");
		add("奇", "strange", "qí");
		add("川", "stream", "chuān");
		add("州", "state", "zhōu");
		add("顺", "obey", "shùn");
		add("水", "water", "shǔi");
		add("永", "eternity", "yǒng");
		add("脉", "blood vessels", "mài");
		add("求", "request", "qíu");
		add("泉", "spring", "quán");
		add("原", "flatlands", "yuán");
		add("泳", "swim", "yǒng");
		add("洲", "continent", "zhōu");
		add("沼", "marsh", "zhǎo");
		add("沙", "sand", "shā");
		add("江", "Yangtze", "jiāng");
		add("汁", "juice", "zhī");
		add("潮", "tide", "cháo");
		add("源", "source", "yuán");
		add("活", "lively", "húo");
		add("消", "extinguish", "xiāo");
		add("河", "river", "hé");
		add("鱼", "fish", "yú");
		add("渔", "fishing", "yú");
		add("湖", "lake", "hú");
		add("测", "fathom", "cè");
		add("土", "soil", "tǔ");
		add("均", "equal", "jūn");
		add("肚", "belly", "dù");
		add("尘", "dust", "chén");
		add("填", "fill in", "tián");
		add("吐", "spit", "tǔ");
		add("压", "pressure", "yā");
		add("哇", "waaah!", "wā");
		add("寸", "Chinese inch", "cùn");
		add("封", "seal", "fēng");
		add("时", "time", "shí");
		add("寺", "Buddhist temple", "sì");
		add("火", "fire", "hǔo");
		add("灭", "destroy", "miè");
		add("灰", "ashes", "hūi");
		add("烦", "vexed", "fán");
		add("炎", "inflammation", "yán");
		add("淡", "thin", "dàn");
		add("灯", "lamp", "dēng");
		add("点", "spot", "diǎn");
		add("照", "illuminate", "zhào");
		add("里", "li", "lǐ");
		add("量", "quantity", "liàng");
		add("埋", "bury", "mái");
		add("黑", "black", "hēi");
		add("墨", "black ink", "mò");
		add("冒", "risk", "mào");
		add("同", "same", "tóng");
		add("洞", "cave", "dòng");
		add("丽", "lovely", "lì");
		add("向", "orientation", "xiàng");
		add("响", "echo", "xiǎng");
		add("尚", "esteem", "shàng");
		add("字", "character", "zì");
		add("守", "guard", "shǒu");
		add("完", "finish", "wán");
		add("灾", "disaster", "zāi");
		add("宣", "proclaim", "xuān");
		add("宵", "nighttime", "xiāo");
		add("安", "peaceful", "ān");
		add("宴", "banquet", "yàn");
		add("寄", "mail", "jì");
		add("富", "wealthy", "fù");
		add("贮", "store up", "zhǔ");
		add("木", "tree", "mù");
		add("林", "woods", "lín");
		add("森", "forest", "sēn");
		add("梦", "dream", "mèng");
		add("机", "machine", "jī");
		add("植", "plant", "zhí");
		add("杏", "apricot", "xìng");
		add("呆", "dim-witted", "dāi");
		add("枯", "withered", "kū");
		add("村", "village", "cūn");
		add("相", "one another", "xiāng");
		add("本", "notebook", "bĕn");
		add("案", "case", "àn");
		add("未", "not yet", "wèi");
		add("末", "last", "mò");
		add("沫", "foam", "mò");
		add("味", "flavor", "wèi");
		add("妹", "younger sister", "mèi");
		add("查", "investigate", "chá");
		add("渣", "sediment", "zhā");
		add("染", "dye", "rǎn");
		add("李", "plum", "lǐ");
		add("桌", "table", "zhūo");
		add("杂", "miscellaneous", "zá");
		add("若", "as if", "rùo");
		add("草", "grass", "cǎo");
		add("艺", "technique", "yì");
		add("苦", "suffering", "kǔ");
		add("宽", "wide", "kuān");
		add("莫", "nobody", "mò");
		add("模", "imitate", "mó");
		add("漠", "desert", "mò");
		add("墓", "grave", "mù");
		add("苗", "seedling", "miáo");
		add("瞄", "aim", "miáo");
		add("兆", "portent", "zhào");
		add("桃", "peach", "táo");
		add("犬", "pooch", "quǎn");
		add("尤", "remarkable", "yóu");
		add("厌", "detest", "yàn");
		add("状", "state of affairs", "zhuàng");
		add("妆", "put on makeup", "zhuāng");
		add("将", "general (military rank)", "jiāng");
		add("获", "seize", "hùo");
		add("默", "silent", "mò");
		add("然", "sort of thing", "rán");
		add("哭", "cry", "kū");
		add("器", "utensil", "qì");
		add("臭", "stinking", "chòu");
		add("狗", "dog", "gǒu");
		add("牛", "cow", "níu");
		add("特", "special", "tè");
		add("告", "declare", "gào");
		add("浩", "vast", "hào");
		add("先", "before", "xiān");
		add("洗", "wash", "xǐ");
		add("个", "individual", "gè");
		add("介", "introduce", "jiè");
		add("界", "world", "jiè");
		add("茶", "tea", "chá");
		add("合", "fit", "hé");
		add("哈", "ha!", "hā");
		add("塔", "pagoda", "tǎ");
		add("王", "king", "wáng");
		add("玉", "jade", "yù");
		add("宝", "treasure", "bǎo");
		add("球", "ball", "qíu");
		add("现", "present", "xiàn");
		add("玩", "play", "wán");
		add("狂", "crazy", "kuáng");
		add("皇", "emperor", "huáng");
		add("煌", "resplendent", "huáng");
		add("呈", "submit", "chéng");
		add("全", "whole", "quán");
		add("理", "logic", "lǐ");
		add("主", "lord", "zhǔ");
		add("注", "pour", "zhù");
		add("金", "gold", "jīn");
		add("钟", "bell", "zhōng");
		add("铜", "copper", "tóng");
		add("钓", "go fishin’", "diào");
		add("针", "needle", "zhēn");
		add("钉", "nail", "dīng");
		add("铭", "inscription", "míng");
		add("镇", "at ease", "zhèn");
		add("道", "way", "dào");
		add("达", "reach", "dá");
		add("远", "distant", "yuǎn");
		add("适", "suitable", "shì");
		add("过", "cross", "gùo");
		add("迈", "stride", "mài");
		add("迅", "speedy", "xùn");
		add("造", "create", "zào");
		add("逃", "escape", "táo");
		add("巡", "patrol", "xún");
		add("选", "choose", "xuǎn");
		add("逊", "modest", "xùn");
		add("逛", "stroll", "guàng");
		add("车", "car", "chē");
		add("连", "one after another", "lián");
		add("莲", "lotus", "lián");
		add("前", "in front", "qián");
		add("剪", "shears", "jiǎn");
		add("输", "transport", "shū");
		add("逾", "exceed", "yú");
		add("条", "strip", "tiáo");
		add("处", "location", "chù");
		add("各", "each", "gè");
		add("格", "pattern", "gé");
		add("略", "abbreviation", "lv");
		add("客", "guest", "kè");
		add("额", "forehead", "é");
		add("夏", "summer", "xià");
		add("洛", "l.a.", "lùo");
		add("落", "fall", "lùo");
		add("备", "prepare", "bèi");
		add("冗", "superfluous", "rǒng");
		add("沉", "profound", "chén");
		add("军", "army", "jūn");
		add("辉", "radiance", "hūi");
		add("冠", "crown", "guān");
		add("坑", "pit", "kēng");
		add("亩", "chinese acre", "mǔ");
		add("高", "tall", "gāo");
		add("享", "enjoy", "xiǎng");
		add("熟", "ripe", "shú");
		add("亭", "pavilion", "tíng");
		add("亮", "shiny", "liàng");
		add("京", "capital", "jīng");
		add("景", "scenery", "jǐng");
		add("就", "at once", "jìu");
		add("周", "circumference", "zhōu");
		add("士", "soldier", "shì");
		add("吉", "lucky", "jí");
		add("壮", "robust", "zhuàng");
		add("学", "study", "xué");
		add("觉", "senses", "jué");
		add("攻", "attack", "gōng");
		add("敌", "enemy", "dí");
		add("败", "fail", "bài");
		add("故", "deliberately", "gù");
		add("救", "rescue", "jìu");
		add("敬", "revere", "jìng");
		add("敞", "spacious", "chǎng");
		add("言", "say", "yán");
		add("警", "police", "jǐng");
		add("计", "plan", "jì");
		add("让", "yield", "ràng");
		add("狱", "prison", "yù");
		add("讨", "condemn", "tǎo");
		add("训", "instructions", "xùn");
		add("识", "knowledge", "shì");
		add("话", "talk", "huà");
		add("诗", "poem", "shī");
		add("语", "language", "yǔ");
		add("调", "tune", "diào");
		add("谈", "discuss", "tán");
		add("式", "style", "shì");
		add("试", "test", "shì");
		add("戈", "halberd", "gē");
		add("战", "war", "zhàn");
		add("划", "scratch", "huá");
		add("或", "or", "hùo");
		add("贼", "burglar", "zéi");
		add("载", "laden", "zài");
		add("茂", "lush", "mào");
		add("成", "turn into", "chéng");
		add("城", "city", "chéng");
		add("诚", "sincere", "chéng");
		add("威", "might", "wēi");
		add("咸", "salty", "xián");
		add("钱", "coin", "qián");
		add("浅", "shallow", "qiǎn");
		add("贱", "cheap", "jiàn");
		add("尧", "yao", "yáo");
		add("烧", "fever", "shāo");
		add("晓", "dawn", "xiǎo");
		add("止", "stop", "zhǐ");
		add("步", "footstep", "bù");
		add("涉", "ford", "shè");
		add("频", "repeatedly", "pín");
		add("肯", "agree", "kĕn");
		add("企", "look forward to", "qǐ");
		add("武", "military", "wǔ");
		add("赋", "levy", "fù");
		add("正", "correct", "zhèng");
		add("证", "evidence", "zhèng");
		add("政", "politics", "zhèng");
		add("定", "settle on", "dìng");
		add("走", "walk", "zǒu");
		add("超", "transcend", "chāo");
		add("越", "surpass", "yuè");
		add("是", "be", "shì");
		add("题", "topic", "tí");
		add("延", "prolong", "yán");
		add("诞", "nativity", "dàn");
		add("建", "build", "jiàn");
		add("楚", "clear", "chǔ");
		add("衣", "clothing", "yī");
		add("裁", "tailor", "cái");
		add("装", "attire", "zhuāng");
		add("哀", "grief", "āi");
		add("袁", "yuan", "yuán");
		add("初", "elementary", "chū");
		add("补", "patch", "bǔ");
		add("衬", "inner garments", "chèn");
		add("农", "agriculture", "nóng");
		add("浓", "concentrated", "nóng");
		add("巾", "towel", "jīn");
		add("帅", "commander", "shuài");
		add("师", "teacher", "shī");
		add("狮", "lion", "shī");
		add("布", "cloth", "bù");
		add("帜", "streamer", "zhì");
		add("帽", "hat", "mào");
		add("幕", "curtain", "mù");
		add("棉", "cotton", "mián");
		add("市", "market", "shì");
		add("肺", "lungs", "fèi");
		add("带", "sash", "dài");
		add("滞", "stagnant", "zhì");
		add("刺", "thorn", "cì");
		add("制", "system", "zhì");
		add("雨", "rain", "yǔ");
		add("雷", "thunder", "léi");
		add("霜", "frost", "shuāng");
		add("云", "cloud", "yún");
		add("运", "carry", "yùn");
		add("冰", "ice", "bīng");
		add("况", "situation", "kuàng");
		add("冲", "collide", "chōng");
		add("减", "reduce", "jiǎn");
		add("凉", "cool", "liáng");
		add("冬", "winter", "dōng");
		add("天", "heavens", "tiān");
		add("吴", "wu", "wú");
		add("娱", "amusement", "yú");
		add("误", "error", "wù");
		add("夭", "die young", "yāo");
		add("乔", "pretend", "qiáo");
		add("桥", "bridge", "qiáo");
		add("娇", "attractive", "jiāo");
		add("立", "standing up", "lì");
		add("泣", "weep", "qì");
		add("站", "station", "zhàn");
		add("章", "chapter", "zhāng");
		add("竞", "compete", "jìng");
		add("帝", "sovereign", "dì");
		add("童", "juvenile", "tóng");
		add("商", "salesman", "shāng");
		add("滴", "drip", "dī");
		add("匕", "ancient spoon", "bǐ");
		add("北", "north", "bĕi");
		add("背", "back", "bèi");
		add("比", "compare", "bǐ");
		add("昆", "descendants", "kūn");
		add("混", "mix", "hùn");
		add("皆", "all", "jiē");
		add("此", "this (literary)", "cǐ");
		add("些", "somewhat", "xiē");
		add("它", "it", "tā");
		add("旨", "purpose", "zhǐ");
		add("脂", "grease", "zhī");
		add("论", "theory", "lùn");
		add("轮", "wheel", "lún");
		add("每", "every", "mĕi");
		add("梅", "small plum", "méi");
		add("海", "sea", "hǎi");
		add("乞", "beg", "qǐ");
		add("吃", "eat", "chī");
		add("复", "duplicate", "fù");
		add("腹", "abdomen", "fù");
		add("欠", "lack", "qiàn");
		add("吹", "blow", "chūi");
		add("歌", "song", "gē");
		add("软", "soft", "ruǎn");
		add("次", "next", "cì");
		add("资", "assets", "zī");
		add("姿", "looks", "zī");
		add("咨", "consult with", "zī");
		add("赔", "compensate", "péi");
		add("培", "cultivate", "péi");
		add("音", "sound", "yīn");
		add("暗", "dark", "àn");
		add("韵", "rhyme", "yùn");
		add("竟", "unexpectedly", "jìng");
		add("镜", "mirror", "jìng");
		add("境", "boundary", "jìng");
		add("亡", "deceased", "wáng");
		add("盲", "blind", "máng");
		add("妄", "absurd", "wàng");
		add("望", "expect", "wàng");
		add("方", "direction", "fāng");
		add("妨", "hinder", "fáng");
		add("放", "release", "fàng");
		add("激", "excite", "jī");
		add("旁", "side", "páng");
		add("兑", "convert", "dùi");
		add("脱", "undress", "tūo");
		add("说", "speak", "shūo");
		add("曾", "formerly", "céng");
		add("增", "increase", "zēng");
		add("赠", "make a present of", "zèng");
		add("也", "also", "yĕ");
		add("她", "she", "tā");
		add("地", "ground", "dì");
		add("池", "pond", "chí");
		add("虫", "insect", "chóng");
		add("虾", "shrimp", "xiā");
		add("独", "alone", "dú");
		add("虽", "although", "sūi");
		add("蛇", "serpent", "shé");
		add("蛋", "egg", "dàn");
		add("己", "self", "jǐ");
		add("起", "begin", "qǐ");
		add("改", "alter", "gǎi");
		add("记", "remember", "jì");
		add("已", "already", "yǐ");
		add("包", "wrap", "bāo");
		add("泡", "bubbles", "pào");
		add("导", "guide", "dǎo");
		add("顾", "look back", "gù");
		add("逐", "pursue", "zhú");
		add("家", "house", "jiā");
		add("场", "site", "cháng");
		add("汤", "soup", "tāng");
		add("羊", "sheep", "yáng");
		add("美", "beautiful", "mĕi");
		add("洋", "ocean", "yáng");
		add("鲜", "fresh", "xiān");
		add("样", "appearance", "yáng");
		add("兰", "orchid", "lán");
		add("烂", "spoiled", "làn");
		add("差", "fall short of", "chà");
		add("着", "-ing", "zháo");
		add("养", "raise", "yǎng");
		add("集", "gather", "jí");
		add("准", "standard", "zhǔn");
		add("谁", "who?", "shúi");
		add("售", "vend", "shòu");
		add("午", "noon", "wǔ");
		add("许", "permit", "xǔ");
		add("羽", "feathers", "yǔ");
		add("习", "learn", "xí");
		add("翔", "soar", "xiáng");
		add("困", "trapped", "kùn");
		add("固", "solid", "gù");
		add("国", "country", "gúo");
		add("圆", "round", "yuán");
		add("因", "cause", "yīn");
		add("烟", "smoke", "yān");
		add("园", "park", "yuán");
		add("回", "return", "húi");
		add("图", "picture", "tú");
		add("广", "extensive", "yǎn");
		add("店", "store", "diàn");
		add("库", "warehouse", "kù");
		add("裤", "trousers", "kù");
		add("床", "bed", "chuáng");
		add("麻", "hemp", "má");
		add("庄", "hamlet", "zhuāng");
		add("心", "heart", "xīn");
		add("忘", "forget", "wàng");
		add("忍", "endure", "rĕn");
		add("总", "general", "zǒng");
		add("态", "attitude", "tài");
		add("志", "aspiration", "zhì");
		add("思", "consider", "sī");
		add("恩", "kindness", "ēn");
		add("愿", "wish", "yuàn");
		add("意", "idea", "yì");
		add("想", "think", "xiǎng");
		add("息", "breath", "xī");
		add("恐", "fear", "kǒng");
		add("感", "feel", "gǎn");
		add("憾", "regret", "hàn");
		add("忧", "worried", "yōu");
		add("惊", "startled", "liáng");
		add("怕", "dread", "pà");
		add("忙", "busy", "máng");
		add("惯", "accustomed to", "guàn");
		add("必", "certainly", "bì");
		add("手", "hand", "shǒu");
		add("看", "look at", "kàn");
		add("摩", "rub", "mó");
		add("拿", "hold", "ná");
		add("我", "i", "wǒ");
		add("抱", "embrace", "bào");
		add("抗", "combat", "kàng");
		add("批", "criticize", "pī");
		add("招", "beckon", "zhāo");
		add("打", "strike", "dǎ");
		add("指", "finger", "zhǐ");
		add("持", "support", "chí");
		add("担", "assume", "dàn");
		add("括", "include", "kùo");
		add("提", "bring up", "tí");
		add("挥", "brandish", "hūi");
		add("推", "push", "tūi");
		add("搅", "stir", "jiǎo");
		add("执", "clench", "zhí");
		add("热", "heat", "rè");
		add("接", "welcome", "jiē");
		add("挂", "hang", "guà");
		add("按", "press down on", "àn");
		add("掉", "drop", "diào");
		add("拉", "pull", "lā");
		add("啦", "!!", "la");
		add("找", "look for", "zhǎo");
		add("无", "nothing", "wú");
		add("抚", "comfort", "fǔ");
		add("开", "open", "kāi");
		add("研", "grind away", "yán");
		add("弄", "play with", "nòng");
		add("异", "different", "yì");
		add("鼻", "nose", "bí");
		add("刑", "punishment", "xíng");
		add("型", "mold", "xíng");
		add("才", "genius", "cái");
		add("财", "riches", "cái");
		add("团", "troupe", "tuán");
		add("存", "deposit", "cún");
		add("在", "at", "zài");
		add("乃", "only then", "nǎi");
		add("奶", "milk", "nǎi");
		add("及", "catch up with", "jí");
		add("吸", "inhale", "xī");
		add("极", "extreme", "jí");
		add("史", "history", "shǐ");
		add("更", "even more", "gèng");
		add("硬", "hard", "yìng");
		add("又", "again", "yòu");
		add("圣", "holy", "shèng");
		add("友", "friend", "yǒu");
		add("双", "pair", "shuāng");
		add("汉", "han", "yì");
		add("戏", "frolic", "xì");
		add("观", "observe", "guān");
		add("欢", "joyous", "huān");
		add("怪", "peculiar", "guài");
		add("对", "that’s right", "dùi");
		add("树", "timber", "shù");
		add("难", "difficult", "nán");
		add("摊", "vendor’s stand", "tān");
		add("投", "throw", "tóu");
		add("没", "not have", "méi");
		add("设", "establish", "shè");
		add("股", "thigh", "gǔ");
		add("支", "offshoot", "zhī");
		add("技", "skill", "jì");
		add("枝", "branch", "zhī");
		add("叔", "uncle", "shū");
		add("督", "superintend", "dū");
		add("寂", "lonely", "jì");
		add("反", "against", "fǎn");
		add("板", "plank", "bǎn");
		add("返", "go back", "fǎn");
		add("后", "behind", "hòu");
		add("质", "quality", "zhí");
		add("派", "faction", "pài");
		add("乐", "music", "lè");
		add("爪", "claw", "zhuǎ");
		add("抓", "grab", "zhuā");
		add("采", "pick", "cǎi");
		add("菜", "vegetable", "cài");
		add("受", "accept", "shòu");
		add("授", "confer", "shòu");
		add("爱", "love", "ài");
		add("么", "(suffix)", "yāo");
		add("雄", "grand", "xíong");
		add("台", "platform", "tái");
		add("治", "govern", "zhì");
		add("始", "commence", "shǐ");
		add("去", "go", "qù");
		add("法", "method", "fǎ");
		add("会", "meeting", "hùi");
		add("至", "until", "zhì");
		add("室", "room", "shì");
		add("到", "arrive", "dào");
		add("互", "mutual", "hù");
		add("充", "sufficient", "chōng");
		add("育", "education", "yù");
		add("流", "flow", "líu");
		add("梳", "comb", "shū");
		add("购", "purchase", "gòu");
		add("构", "frame", "gōu");
		add("山", "mountain", "shān");
		add("出", "exit", "chū");
		add("础", "foundation", "chǔ");
		add("岁", "years of age", "sùi");
		add("密", "secret", "mì");
		add("入", "enter", "rù");
		add("分", "part", "fēn");
		add("贫", "impoverished", "pín");
		add("公", "public", "gōng");
		add("松", "pine tree", "sōng");
		add("谷", "valley", "gǔ");
		add("浴", "bathe", "yù");
		add("欲", "desire", "yù");
		add("容", "contain", "róng");
		add("溶", "dissolve", "róng");
		add("赏", "prize", "shǎng");
		add("党", "political party", "dǎng");
		add("常", "often", "cháng");
		add("堂", "main room", "táng");
		add("皮", "covering", "pí");
		add("波", "waves", "bō");
		add("婆", "old woman", "pó");
		add("破", "break", "pò");
		add("被", "quilt", "bèi");
		add("歹", "malicious", "dǎi");
		add("列", "line up", "liè");
		add("烈", "intense", "liè");
		add("死", "death", "sǐ");
		add("葬", "inter", "zàng");
		add("耳", "ear", "ĕr");
		add("取", "take", "qǔ");
		add("趣", "interest", "qù");
		add("最", "most", "zùi");
		add("职", "job", "zhí");
		add("敢", "brave", "gǎn");
		add("曼", "drawn out", "màn");
		add("慢", "slow", "màn");
		add("漫", "overflow", "màn");
		add("夫", "husband", "fū");
		add("规", "regulations", "gūi");
		add("替", "replace", "tì");
		add("失", "lose", "shī");
		add("铁", "iron", "tiĕ");
		add("臣", "feudal official", "chén");
		add("力", "power", "lì");
		add("边", "border", "biān");
		add("势", "force", "shì");
		add("动", "move", "dòng");
		add("励", "encourage", "lì");
		add("历", "experience", "lì");
		add("另", "another", "lìng");
		add("别", "don’t", "bié");
		add("拐", "turn", "guǎi");
		add("男", "male", "nán");
		add("功", "achievement", "gōng");
		add("办", "manage", "bàn");
		add("协", "cooperate", "xié");
		add("苏", "revive", "sū");
		add("为", "act", "wèi");
		add("奴", "slave", "nú");
		add("努", "toil", "nǔ");
		add("加", "add", "jiā");
		add("贺", "congratulate", "hè");
		add("架", "shelf", "jià");
		add("务", "tasks", "wù");
		add("雾", "fog", "wù");
		add("行", "line of business", "xíng");
		add("律", "law", "lǜ");
		add("得", "must", "dé");
		add("待", "treat", "dài");
		add("往", "toward", "wǎng");
		add("德", "morality", "dé");
		add("微", "tiny", "wēi");
		add("街", "street", "jiē");
		add("禾", "standing grain", "hé");
		add("程", "journey", "chéng");
		add("和", "harmony", "hé");
		add("积", "accumulate", "jī");
		add("种", "species", "zhǒng");
		add("移", "shift", "yí");
		add("秋", "autumn", "qīu");
		add("愁", "gloomy", "chóu");
		add("揪", "hold tight", "jīu");
		add("利", "profit", "lì");
		add("香", "perfume", "xiāng");
		add("季", "seasons", "jì");
		add("委", "committee", "wĕi");
		add("秀", "elegant", "xìu");
		add("透", "penetrate", "tòu");
		add("诱", "entice", "yòu");
		add("米", "rice", "mǐ");
		add("粉", "powder", "fĕn");
		add("迷", "lost", "mí");
		add("谜", "riddle", "mí");
		add("类", "kind", "lèi");
		add("来", "come", "lái");
		add("数", "number", "shù");
		add("楼", "multistory building", "lóu");
		add("竹", "bamboo", "zhú");
		add("笑", "laugh", "xiào");
		add("箱", "box", "xiāng");
		add("等", "etc.", "dĕng");
		add("算", "calculate", "suàn");
		add("答", "answer", "dá");
		add("策", "strategy", "cè");
		add("人", "person", "rén");
		add("认", "recognize", "rèn");
		add("价", "price", "jià");
		add("份", "portion", "fèn");
		add("伪", "bogus", "wĕi");
		add("尔", "you (literary)", "ĕr");
		add("你", "you", "nǐ");
		add("您", "you (respectful)", "nín");
		add("称", "weigh", "chēng");
		add("什", "what?", "shí");
		add("值", "value", "zhí");
		add("做", "make", "zùo");
		add("但", "however", "dàn");
		add("住", "dwell", "zhù");
		add("位", "position", "wèi");
		add("件", "piece", "jiàn");
		add("仍", "still", "réng");
		add("他", "he", "tā");
		add("仅", "merely", "jǐn");
		add("休", "rest", "xīu");
		add("体", "body", "tǐ");
		add("信", "faith", "xìn");
		add("依", "depend on", "yī");
		add("例", "example", "lì");
		add("健", "healthy", "jiàn");
		add("停", "halt", "tíng");
		add("倒", "upside down", "dǎo");
		add("仁", "benevolence", "rén");
		add("优", "excellent", "yōu");
		add("伤", "wound", "shāng");
		add("保", "safeguard", "bǎo");
		add("堡", "fort", "bǎo");
		add("付", "pay", "fù");
		add("府", "government office", "fǔ");
		add("俯", "bow one’s head", "fǔ");
		add("代", "substitute for", "dài");
		add("袋", "bag", "dài");
		add("化", "transform", "huà");
		add("华", "splendor", "huá");
		add("哗", "clamor", "huā");
		add("花", "flower", "huā");
		add("货", "commodities", "hùo");
		add("何", "whatwhichwhowherewhy?", "hé");
		add("便", "convenient", "biàn");
		add("丈", "100 chinese inches", "zhàng");
		add("使", "use", "shǐ");
		add("久", "long time", "jǐu");
		add("内", "internal", "nèi");
		add("呐", "holler", "nè");
		add("丙", "third", "bǐng");
		add("柄", "handle", "bǐng");
		add("肉", "meat", "ròu");
		add("腐", "rotten", "fǔ");
		add("从", "follow", "cóng");
		add("众", "multitude", "zhòng");
		add("坐", "sit", "zùo");
		add("座", "seat", "zùo");
		add("巫", "witch", "wū");
		add("喝", "drink", "hē");
		add("渴", "thirsty", "kĕ");
		add("任", "appoint", "rèn");
		add("廷", "royal court", "tíng");
		add("庭", "court of law", "tíng");
		add("头", "head", "tóu");
		add("实", "reality", "shí");
		add("买", "buy", "mǎi");
		add("卖", "sell", "mài");
		add("读", "read", "dú");
		add("以", "by means of", "yǐ");
		add("似", "similar", "sì");
		add("并", "combine", "bìng");
		add("拼", "piece together", "pīn");
		add("吕", "spine", "lǚ");
		add("侣", "associate", "lǚ");
		add("荣", "glory", "róng");
		add("劳", "labor", "láo");
		add("营", "camp", "yíng");
		add("善", "virtuous", "shàn");
		add("年", "year", "nián");
		add("夜", "night", "yè");
		add("液", "liquid", "yè");
		add("旅", "travel", "lǚ");
		add("施", "execute", "shī");
		add("游", "go swimming", "yóu");
		add("勿", "not", "wù");
		add("忽", "suddenly", "hū");
		add("物", "thing", "wù");
		add("易", "easy", "yì");
		add("赐", "grant", "sì");
		add("尸", "corpse", "shī");
		add("尼", "nun", "ní");
		add("呢", "woolen cloth", "ní");
		add("泥", "mud", "ní");
		add("屋", "habitation", "wū");
		add("握", "grip", "wò");
		add("居", "reside", "jū");
		add("锯", "saw", "jù");
		add("剧", "drama", "jù");
		add("据", "certificate", "jù");
		add("层", "story", "céng");
		add("局", "bureau", "jú");
		add("尺", "ruler", "chǐ");
		add("尽", "exhausted", "jǐn");
		add("户", "door", "hù");
		add("房", "domicile", "fáng");
		add("雇", "hire", "gù");
		add("护", "protect", "hù");
		add("示", "show", "shì");
		add("社", "society", "shè");
		add("礼", "ceremony", "lǐ");
		add("视", "inspect", "shì");
		add("福", "happiness", "fú");
		add("标", "mark", "biāo");
		add("禁", "prohibit", "jìn");
		add("襟", "front of a garment", "jīn");
		add("宗", "religion", "zōng");
		add("崇", "worship", "chóng");
		add("祭", "offer sacrifice", "jì");
		add("察", "scrutinize", "chá");
		add("擦", "scrub", "cā");
		add("由", "wherefore", "yóu");
		add("抽", "take out", "chōu");
		add("油", "oil", "yóu");
		add("甲", "first", "jiǎ");
		add("押", "pawn", "yā");
		add("申", "express", "shēn");
		add("伸", "extend", "shēn");
		add("神", "gods", "shén");
		add("果", "fruit", "gǔo");
		add("课", "lesson", "kè");
		add("颗", "granule", "kē");
		add("斤", "catty", "jīn");
		add("听", "listen", "tīng");
		add("所", "place", "sǔo");
		add("近", "near", "jìn");
		add("斩", "hew", "zhǎn");
		add("暂", "temporary", "zàn");
		add("渐", "gradually", "jiàn");
		add("断", "sever", "duàn");
		add("折", "discount", "zhé");
		add("哲", "philosopher", "zhé");
		add("逝", "pass away", "shì");
		add("斥", "reprimand", "chì");
		add("诉", "accuse", "sù");
		add("乍", "for the first time", "zhà");
		add("怎", "how?", "zĕn");
		add("昨", "yesterday", "zúo");
		add("作", "do", "zùo");
		add("雪", "snow", "xuĕ");
		add("灵", "spirit", "líng");
		add("妇", "married woman", "fù");
		add("扫", "sweep", "sǎo");
		add("寻", "seek", "xún");
		add("急", "anxious", "jí");
		add("当", "work as", "dāng");
		add("档", "files", "dǎng");
		add("录", "record", "lù");
		add("碌", "commonplace", "lù");
		add("争", "contend", "zhēng");
		add("净", "clean", "jìng");
		add("事", "matter", "shì");
		add("唐", "tang", "táng");
		add("糖", "sugar", "táng");
		add("康", "hale", "kāng");
		add("尹", "overseer", "yǐn");
		add("伊", "queen elizabeth", "yī");
		add("君", "monarch", "jūn");
		add("裙", "skirt", "qún");
		add("群", "crowd", "qún");
		add("而", "and", "ér");
		add("需", "need", "xū");
		add("儒", "confucian", "rú");
		add("瑞", "auspicious", "rùi");
		add("端", "upright", "duān");
		add("曲", "bent", "qū");
		add("斗", "big dipper", "dǒu");
		add("料", "material", "liào");
		add("科", "academic discipline", "kē");
		add("用", "utilize", "yòng");
		add("确", "reliable", "què");
		add("昔", "times past", "xī");
		add("借", "borrow", "jiè");
		add("错", "mistaken", "cùo");
		add("散", "scattered", "sàn");
		add("撒", "scatter", "sā");
		add("廿", "twenty", "niàn");
		add("席", "mat", "xí");
		add("度", "degrees", "dù");
		add("渡", "ferry", "dù");
		add("半", "half", "bàn");
		add("伴", "partner", "bàn");
		add("胖", "fat", "pàng");
		add("判", "judge", "pàn");
		add("眷", "dependents", "juàn");
		add("拳", "boxing", "quán");
		add("片", "slice", "piàn");
		add("版", "printing plate", "bǎn");
		add("之", "of", "zhī");
		add("乏", "weary", "fá");
		add("眨", "blink", "zhǎ");
		add("不", "no", "bù");
		add("否", "negate", "fǒu");
		add("坏", "bad", "huài");
		add("环", "ring", "huán");
		add("杯", "cup", "bēi");
		add("还", "give back", "huán");
		add("怀", "cherish", "huái");
		add("矢", "dart", "shǐ");
		add("族", "tribe", "zú");
		add("知", "know", "zhī");
		add("智", "wisdom", "zhì");
		add("矛", "spear", "máo");
		add("柔", "gentle", "róu");
		add("揉", "knead", "róu");
		add("予", "bestow", "yú");
		add("序", "preface", "xù");
		add("预", "beforehand", "yù");
		add("野", "wild", "yĕ");
		add("班", "class", "bān");
		add("临", "be about to", "lín");
		add("坚", "firm", "jiān");
		add("贤", "worthy", "xián");
		add("弓", "bow", "gōng");
		add("引", "draw", "yǐn");
		add("弥", "fill", "mí");
		add("强", "strong", "qiáng");
		add("弱", "weak", "rùo");
		add("单", "list", "dān");
		add("弹", "bullet", "dàn");
		add("费", "expense", "fèi");
		add("佛", "buddha", "fó");
		add("弟", "younger brother", "dì");
		add("第", "no.", "dì");
		add("巧", "adroit", "qiǎo");
		add("号", "appellation", "hào");
		add("身", "somebody", "shēn");
		add("射", "shoot", "shè");
		add("谢", "thank", "xiè");
		add("老", "old man", "lǎo");
		add("考", "take an exam", "kǎo");
		add("烤", "roast", "kǎo");
		add("与", "offer", "yǔ");
		add("写", "write", "xiĕ");
		add("泻", "diarrhea", "xiè");
		add("孝", "filial piety", "xiào");
		add("教", "teach", "jiào");
		add("者", "someone", "zhĕ");
		add("著", "author", "zhù");
		add("猪", "pig", "zhū");
		add("追", "chase", "zhūi");
		add("官", "bureaucrat", "guān");
		add("管", "pipe", "guǎn");
		add("父", "father", "fù");
		add("交", "mingle", "jiāo");
		add("效", "effect", "xiào");
		add("较", "relatively", "jiào");
		add("校", "school", "xiào");
		add("足", "lower leg", "zú");
		add("跑", "run", "pǎo");
		add("跳", "jump", "tiào");
		add("路", "path", "lù");
		add("露", "dew", "lù");
		add("骨", "skeleton", "gǔ");
		add("滑", "slippery", "huá");
		add("阿", "apollo", "ā");
		add("啊", "aah!", "a");
		add("随", "as you wish", "súi");
		add("阳", "yang", "yáng");
		add("阴", "yin", "yīn");
		add("荫", "shady", "yìn");
		add("防", "ward off", "fáng");
		add("附", "attach", "fù");
		add("际", "occasion", "jì");
		add("阶", "stairs", "jiē");
		add("院", "inst.", "yuàn");
		add("阵", "battle formation", "zhèn");
		add("队", "team", "dùi");
		add("坠", "crash", "zhùi");
		add("降", "descend", "jiàng");
		add("穴", "hole", "xué");
		add("究", "research", "jīu");
		add("突", "abruptly", "tū");
		add("空", "empty", "kōng");
		add("控", "control", "kòng");
		add("深", "deep", "shēn");
		add("探", "spy", "tàn");
		add("丘", "hill", "qīu");
		add("兵", "troops", "bīng");
		add("丝", "silk", "sī");
		add("织", "weave", "zhī");
		add("线", "line", "xiàn");
		add("维", "maintain", "wéi");
		add("统", "overall", "tǒng");
		add("给", "give", "gĕi");
		add("结", "tie", "jié");
		add("终", "end", "zhōng");
		add("级", "rank", "jí");
		add("纪", "epoch", "jì");
		add("红", "red", "hóng");
		add("约", "make an appointment", "yuē");
		add("细", "fine", "xì");
		add("纵", "vertical", "zòng");
		add("绿", "green", "lǜ");
		add("经", "scripture", "jīng");
		add("轻", "lightweight", "qīng");
		add("续", "continue", "xù");
		add("继", "carry on", "jì");
		add("药", "medicine", "yào");
		add("系", "lineage", "xì");
		add("紧", "tight", "jǐn");
		add("却", "withdraw", "què");
		add("脚", "foot", "jiǎo");
		add("服", "apparel", "fú");
		add("报", "newspaper", "bào");
		add("命", "fate", "mìng");
		add("贸", "trade", "mào");
		add("留", "stay", "líu");
		add("溜", "slide", "līu");
		add("聊", "chat", "liáo");
		add("柳", "willow", "lǐu");
		add("节", "holiday", "jié");
		add("卫", "defend", "wèi");
		add("令", "orders", "lìng");
		add("冷", "cold", "lĕng");
		add("零", "zero", "líng");
		add("领", "collar", "lǐng");
		add("通", "communicate", "tōng");
		add("勇", "courageous", "yǒng");
		add("仓", "storehouse", "cāng");
		add("枪", "gun", "qiāng");
		add("创", "initiate", "chuàng");
		add("犯", "criminal", "fàn");
		add("危", "danger", "wēi");
		add("脆", "fragile", "cùi");
		add("印", "print", "yìn");
		add("酒", "liquor", "jǐu");
		add("配", "distribute", "pèi");
		add("酋", "chieftain", "qíu");
		add("尊", "venerate", "zūn");
		add("遵", "abide by", "zūn");
		add("豆", "beans", "dòu");
		add("短", "short", "duǎn");
		add("厨", "kitchen", "chú");
		add("鼓", "drum", "gǔ");
		add("喜", "joyful", "xǐ");
		add("血", "blood", "xiĕ");
		add("盖", "lid", "gài");
		add("温", "temperature", "wēn");
		add("监", "supervise", "jiān");
		add("篮", "basket", "lán");
		add("蓝", "blue", "lán");
		add("银", "silver", "yín");
		add("跟", "heel", "gēn");
		add("很", "very", "hĕn");
		add("根", "root", "gēn");
		add("即", "immediately", "jí");
		add("退", "retreat", "tùi");
		add("腿", "leg", "tǔi");
		add("限", "limit", "xiàn");
		add("眼", "eyelet", "yǎn");
		add("良", "high-quality", "liáng");
		add("浪", "breakers", "làng");
		add("娘", "mom", "niáng");
		add("食", "food", "shí");
		add("饭", "meal", "fàn");
		add("餐", "dine", "cān");
		add("馆", "bldg.", "guǎn");
		add("既", "since", "jì");
		add("概", "approximate", "gài");
		add("平", "even", "píng");
		add("评", "evaluate", "píng");
		add("坪", "level ground", "píng");
		add("乎", "ooh!", "hū");
		add("呼", "shout", "hū");
		add("希", "hope", "xī");
		add("稀", "scarce", "xī");
		add("杀", "kill", "shā");
		add("风", "wind", "fēng");
		add("讽", "mock", "fēng");
		add("冈", "ridge of a hill", "gāng");
		add("刚", "just now", "gāng");
		add("网", "net", "wǎng");
		add("画", "drawing", "huà");
		add("凶", "cruel", "xīong");
		add("胸", "bosom", "xīong");
		add("脑", "brain", "nǎo");
		add("恼", "annoyed", "nǎo");
		add("离", "leave", "lí");
		add("禽", "fowl", "qín");
		add("义", "righteousness", "yì");
		add("议", "deliberate", "yí");
		add("蚁", "ant", "yǐ");
		add("辛", "peppery", "xīn");
		add("辩", "dispute", "biàn");
		add("辟", "repudiate", "pì");
		add("壁", "partition", "bì");
		add("避", "evade", "bì");
		add("亲", "relatives", "qīn");
		add("新", "new", "xīn");
		add("薪", "fuel", "xīn");
		add("幸", "good fortune", "xìng");
		add("叫", "call", "jiào");
		add("收", "receive", "shōu");
		add("亥", "sign of the hog", "hài");
		add("核", "nucleus", "hé");
		add("孩", "tot", "hái");
		add("刻", "carve", "kè");
		add("该", "should", "gāi");
		add("术", "art", "zhú");
		add("述", "narrate", "shù");
		add("襄", "aid", "xiāng");
		add("壤", "territory", "rǎng");
		add("寒", "frigid", "hán");
		add("赛", "competition", "sài");
		add("毒", "poison", "dú");
		add("麦", "wheat", "mài");
		add("素", "vegetarian diet", "sù");
		add("青", "blue or green", "qīng");
		add("精", "refined", "jīng");
		add("请", "invite", "qǐng");
		add("情", "feelings", "qíng");
		add("睛", "eyeball", "jīng");
		add("清", "pure", "qīng");
		add("静", "quiet", "jìng");
		add("责", "responsibility", "zé");
		add("绩", "accomplishments", "jī");
		add("表", "surface", "biǎo");
		add("生", "life", "shēng");
		add("星", "star", "xīng");
		add("姓", "surname", "xìng");
		add("性", "sex", "xìng");
		add("胜", "victory", "shèng");
		add("丰", "plentiful", "fēng");
		add("害", "harm", "hài");
		add("割", "cut off", "gē");
		add("慧", "intelligent", "hùi");
		add("韦", "tanned hide", "wéi");
		add("围", "surround", "wéi");
		add("伟", "great", "wĕi");
		add("春", "springtime", "chūn");
		add("泰", "tranquil", "tài");
		add("奉", "proffer", "fèng");
		add("棒", "cudgel", "bàng");
		add("击", "beat", "jí");
		add("陆", "land", "lù");
		add("专", "specialty", "zhuān");
		add("传", "spread", "chuán");
		add("转", "rotate", "zhuǎn");
		add("勤", "diligent", "qín");
		add("谨", "careful", "jǐn");
		add("垂", "droop", "chúi");
		add("锤", "hammer", "chúi");
		add("睡", "sleep", "shùi");
		add("今", "now", "jīn");
		add("含", "harbor", "hán");
		add("念", "miss", "niàn");
		add("东", "east", "dōng");
		add("栋", "building", "dòng");
		add("冻", "freeze", "dòng");
		add("陈", "exhibit", "chén");
		add("练", "practice", "liàn");
		add("拣", "opt for", "jiǎn");
		add("西", "west", "xī");
		add("要", "want", "yào");
		add("腰", "waist", "yāo");
		add("票", "ticket", "piào");
		add("漂", "drift", "piāo");
		add("贾", "merchant", "jiǎ");
		add("南", "south", "nán");
		add("门", "gate", "mén");
		add("们", "(plural)", "men");
		add("闲", "leisure", "xián");
		add("问", "ask", "wèn");
		add("间", "interval", "jiān");
		add("简", "simple", "jiǎn");
		add("闻", "hear", "wén");
		add("非", "non-", "fēi");
		add("排", "row", "pái");
		add("罪", "guilt", "zùi");
		add("靠", "lean on", "kào");
		add("侯", "marquis", "hóu");
		add("候", "wait", "hòu");
		add("决", "decide", "jué");
		add("快", "fast", "kuài");
		add("块", "lump", "kuài");
		add("筷", "chopsticks", "kuài");
		add("干", "dry", "gān");
		add("岸", "shore", "àn");
		add("旱", "drought", "hàn");
		add("赶", "hurry", "gǎn");
		add("于", "yu", "yú");
		add("宇", "eaves", "yǔ");
		add("余", "excess", "yú");
		add("除", "eliminate", "chú");
		add("途", "route", "tú");
		add("束", "bundle up", "shù");
		add("速", "quick", "sù");
		add("辣", "spicy hot", "là");
		add("整", "entire", "zhĕng");
		add("重", "heavy", "zhòng");
		add("懂", "understand", "dǒng");
		add("病", "illness", "bìng");
		add("痛", "ache", "tòng");
		add("疯", "insane", "fēng");
		add("区", "region", "qū");
		add("枢", "hub", "shū");
		add("欧", "europe", "ōu");
		add("医", "physician", "yì");
		add("仰", "look up to", "yǎng");
		add("迎", "greet", "yíng");
		add("登", "ascend", "dēng");
		add("发", "send out", "fā");
		add("废", "discard", "fèi");
		add("形", "shape", "xíng");
		add("影", "shadow", "yǐng");
		add("彩", "hue", "cǎi");
		add("须", "have to", "xū");
		add("参", "participate", "");
		add("惨", "wretched", "cǎn");
		add("修", "repair", "xīu");
		add("珍", "rare", "zhēn");
		add("产", "products", "chǎn");
		add("彦", "erudite", "yàn");
		add("颜", "countenance", "yán");
		add("文", "literature", "wén");
		add("蚊", "mosquito", "wén");
		add("这", "this", "zhè");
		add("齐", "identical", "qí");
		add("济", "relieve", "jì");
		add("率", "rate", "lǜ");
		add("摔", "tumble", "shuāi");
		add("央", "center", "yāng");
		add("英", "england", "yīng");
		add("唤", "call out", "huàn");
		add("换", "exchange", "huàn");
		add("巴", "crust", "bā");
		add("把", "grasp", "bǎ");
		add("爸", "papa", "bà");
		add("吧", "bar", "ba");
		add("色", "color", "sè");
		add("绝", "discontinue", "jué");
		add("艳", "gorgeous", "yàn");
		add("甘", "sweet", "gān");
		add("某", "such and such", "mǒu");
		add("其", "his-hers-its-theirs", "qí");
		add("期", "period of time", "qī");
		add("基", "base", "jī");
		add("甚", "tremendously", "shén");
		add("斯", "sphinx", "sī");
		add("贵", "expensive", "gùi");
		add("遗", "bequeath", "yí");
		add("舞", "dance", "wǔ");
		add("且", "moreover", "qiĕ");
		add("姐", "older sister", "jiĕ");
		add("组", "group", "zǔ");
		add("祖", "ancestor", "zǔ");
		add("助", "assist", "zhù");
		add("普", "universal", "pǔ");
		add("业", "profession", "yè");
		add("显", "obvious", "xiǎn");
		add("亚", "asia", "yà");
		add("恶", "evil", "è");
		add("严", "strict", "yán");
		add("共", "together", "gòng");
		add("供", "supply", "gōng");
		add("巷", "lane", "xiàng");
		add("港", "port", "gǎng");
		add("井", "well", "jǐng");
		add("讲", "lecture", "jiǎng");
		add("进", "advance", "jìn");
		add("角", "angle", "jiǎo");
		add("解", "untie", "jiĕ");
		add("嘴", "orifice", "zǔi");
		add("再", "once more", "zài");
		add("扁", "flat", "biǎn");
		add("篇", "piece of writing", "piān");
		add("编", "compile", "biān");
		add("典", "canon", "diǎn");
		add("氏", "family name", "shì");
		add("纸", "paper", "zhǐ");
		add("昏", "dusk", "hūn");
		add("婚", "marriage", "hūn");
		add("低", "low", "dī");
		add("底", "bottom", "dǐ");
		add("民", "people", "mín");
		add("眠", "slumber", "mián");
		add("甫", "fu", "fǔ");
		add("辅", "supplement", "fǔ");
		add("博", "knowledgeable", "bó");
		add("搏", "wrestle", "bó");
		add("都", "metropolis", "dū");
		add("部", "department", "bù");
		add("郎", "young man", "láng");
		add("帮", "help", "bāng");
		add("乡", "countryside", "xiāng");
		add("段", "section", "duàn");
		add("锻", "forge", "duàn");
		add("幻", "unreal", "huàn");
		add("司", "take charge of", "sī");
		add("词", "word", "cí");
		add("书", "book", "shū");
		add("舟", "boat", "zhōu");
		add("船", "ship", "chuán");
		add("般", "sort", "bān");
		add("盘", "tray", "pán");
		add("搬", "relocate", "bān");
		add("瓜", "melon", "guā");
		add("孤", "orphan", "gū");
		add("益", "benefit", "yì");
		add("假", "vacation", "jiǎ");
		add("暇", "spare time", "xiá");
		add("气", "air", "qì");
		add("汽", "vapor", "qì");
		add("面", "face-to-face", "miàn");
		add("革", "leather", "gé");
		add("鞋", "shoes", "xié");
		add("勒", "tighten", "lè");
		add("馨", "fragrant", "xīn");
		add("声", "voice", "shēng");
		add("承", "undertake", "chéng");
		add("蒸", "steam", "zhēng");
		add("牙", "tooth", "yá");
		add("穿", "pass through", "chuān");
		add("呀", "wow!", "yā");
		add("释", "explain", "shì");
		add("番", "try", "fān");
		add("翻", "turn over", "fān");
		add("播", "broadcast", "bō");
		add("毛", "fur", "máo");
		add("尾", "tail", "wĕi");
		add("笔", "pen", "bǐ");
		add("托", "entrust", "tūo");
		add("宅", "dwelling", "zhái");
		add("展", "unfold", "zhǎn");
		add("丧", "funeral", "sāng");
		add("长", "long", "cháng");
		add("张", "stretch", "zhāng");
		add("涨", "swell", "zhǎng");
		add("雁", "wild goose", "yàn");
		add("应", "ought to", "yìng");
		add("兴", "excitement", "xīng");
		add("举", "lift up", "jǔ");
		add("检", "examine", "jiǎn");
		add("脸", "face", "liǎn");
		add("险", "perilous", "xiǎn");
		add("鸟", "bird", "niǎo");
		add("鸡", "chicken", "jī");
		add("鹰", "hawk", "yīng");
		add("鸭", "duck", "yā");
		add("岛", "island", "dǎo");
		add("遇", "encounter", "yù");
		add("缺", "deficient", "quē");
		add("遥", "remote", "yáo");
		add("摇", "shake", "yáo");
		add("兔", "rabbit", "tù");
		add("逸", "flee", "yì");
		add("免", "avoid", "miǎn");
		add("晚", "nightfall", "wǎn");
		add("象", "elephant", "xiàng");
		add("像", "likeness", "xiàng");
		add("马", "horse", "mǎ");
		add("妈", "mama", "mā");
		add("吗", "yes or no", "ma");
		add("骂", "scold", "mà");
		add("验", "check", "yàn");
		add("骑", "ride", "qí");
		add("虎", "tiger", "hǔ");
		add("虑", "ponder", "lǜ");
		add("虚", "FALSE", "xū");
		add("鹿", "deer", "lù");
		add("熊", "bear", "xíong");
		add("能", "ability", "néng");
		add("寅", "sign of the tiger", "yín");
		add("演", "perform", "yǎn");
		add("辰", "sign of the dragon", "chén");
		add("晨", "morning", "chén");
		add("关", "shut", "guān");
		add("送", "deliver", "sòng");
		add("联", "unite", "lián");
		add("鬼", "ghost", "gǔi");
		add("魔", "demon", "mó");
		add("龙", "dragon", "lóng");
		add("袭", "raid", "xí");
		add("那", "that", "nà");
		add("哪", "which?", "nǎ");
		add("两", "dos", "liǎng");
		add("俩", "duo", "liǎ");
		add("满", "full", "mǎn");
		add("县", "county", "xiàn");
		add("悬", "suspend", "xuán");
		add("窗", "window", "chuāng");
		add("电", "electricity", "diàn");
		add("掩", "conceal", "yǎn");
		add("丑", "clown", "chǒu");
		add("扭", "twist", "nǐu");
		add("黄", "yellow", "huáng");
		add("横", "horizontal", "héng");
		add("赤", "crimson", "chì");
		add("亦", "likewise", "yì");
		add("弯", "curved", "wān");
		add("湾", "bay", "wān");
		add("恋", "be enamored of", "liàn");
		add("变", "change", "biàn");
		add("卑", "lowly", "bēi");
		add("牌", "brand", "pái");
		add("套", "cover", "tào");
		add("曰", "sayeth", "yuē");
		add("属", "belong to", "shǔ");
	}
	
	private static void add(String character, String keyword, String pinyin) {
		characters.add(character);
		keywords.add(keyword);
		pinyins.add(pinyin);
	}

}
